dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - '8.9.1'

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  - cd devops-maturity-app

before_script:
  - npm install -g @angular/cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - ng build
  - ng test --watch=false
  